name: Node.js CI/CD with Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Deploy if tests pass
      - name: Deploy to Vercel
        if: success()
        run: |
          npm install -g vercel
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}

# name: Node.js CI/CD with Vercel

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up Node.js
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'

#       # Install dependencies
#       - name: Install dependencies
#         run: npm install

#       # Run tests
#       - name: Run tests
#         run: npm test

#       # Deploy if tests pass
#       - name: Deploy to Vercel
#         if: success()
#         run: |
#           npm install -g vercel
#           vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}


# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-test:
#     runs-on: windows-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up Node.js
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16

#       # Install dependencies
#       - name: Install dependencies
#         run: npm install

#       # Run tests
#       - name: Run tests
#         run: npm test
#         continue-on-error: false  # Ensure the workflow will stop if tests fail

#   deploy:
#     runs-on: windows-latest
#     needs: build-and-test  # Ensure that the deployment only runs after 'build-and-test' job
#     if: success()  # Ensure deployment only runs if tests pass

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up Node.js
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       # Install dependencies
#       - name: Install dependencies
#         run: npm install

#       # Deploy to Vercel
#       - name: Deploy to Vercel
#         uses: amondnet/vercel-action@v20
#         with:
#           vercel-token: ${{ secrets.VERCEL_TOKEN }}
#           vercel-args: "--prod --yes"
#           working-directory: ./
