name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment instead of ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to Vercel
        if: success()  # Only deploy if tests pass
        run: |
          npm install -g vercel  # Ensure Vercel CLI is installed
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
